### PR TITLE
Add username recovery page

### LINKED ISSUE #96: Add username recovery to the password reset page
People who don't know their username should be able to supply the email address associated with their account and request that their username be sent to them.

 _Imported from trac ticket [#96](http://trac.gpolab.bbn.com/idp-tools/ticket/96),  created by sedwards on 05-28-2014 at 10:09, last modified: 07-17-2014 at 09:49_

### PR DESCRIPTION
**Pull request by charliemeyer**
Fixes #96

### CODE REVIEW

**Comment by charliemeyer** [comment]
Will do changes file when I know what release to put it under. Also, where would a link to this new page go?

**Comment by tcmitchell** [comment]
What if we put a link to this new page on the password reset page? Would people be able to find it there when they try to reset their password? If not, maybe it goes adjacent to the reset your password link, wherever that is?

It can go in release 1.4 or 1.5. If you want it in the 1.4 release it can be merged right away.

**Comment by charliemeyer** [comment]
I think both places would work fine. I just don't know where there's a link to the password change page. If we can figure that out, I see no reason why it can't go in 1.4

**Comment by tcmitchell** [comment]
There is a link in `www/request.html`. There are also links on pages not in this repository, like the gene-login repository (`webapp/login.jsp`). We can coordinate a release or that link can come later.

**Comment by charliemeyer** [comment]
I'll add a link on request.html, and then make a ticket on geni-login to add the link there?

**Comment by charliemeyer** [comment]
And maybe handle that ticket

**Comment by tcmitchell** [comment]
Great, thanks very much.

**Comment by charliemeyer** [comment]
All ready to merge

**Pull request merged**
